version: 2.1
jobs:
  compile:
    docker:
      - image: fadlyas/my-docker-image:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone --depth=1 https://github.com/timangpopi/android-kernel-xiaomi-msm8917 -b lineage-16.0 .
      - run: git clone --depth=1 https://github.com/timangpopi/Anykernel-both gg
      - run: bash gg/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
      - compiletoo
