version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get -y update && apt-get -y upgrade && apt-get -y install bc binutils python g++ build-essential zip curl libstdc++6 git wget
      - run: git clone --depth=1 https://github.com/timangpopi/android-kernel-xiaomi-msm8917 -b lineage-16.0 .
      - run: wget https://raw.githubusercontent.com/timangpopi/semaphore/master/Circle/GCC-4.9.x-script
      - run: chmod +x GCC-4.9.x-script
      - run: bash GCC-4.9.x-script
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
