version: 2.1
jobs:
  compile:
    docker:
      - image: fadlyas/my-docker-image:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone --depth=1 https://github.com/timangpopi/android-kernel-xiaomi-msm8917 -b lineage-16.0 .
      - run: wget https://raw.githubusercontent.com/timangpopi/semaphore/master/Circle/try
      - run: chmod +x try
      - run: bash try
  compiletoo:
    docker:
      - image: fadlyas/my-docker-image:latest
    steps:
      - run: apt-get -y update && apt-get -y upgrade
      - run: git clone --depth=1 https://github.com/timangpopi/android-kernel-xiaomi-msm8917 -b lineage-16.0 .
      - run: wget https://raw.githubusercontent.com/timangpopi/semaphore/master/Circle/bacod_2
      - run: chmod +x bacod_2
      - run: bash bacod_2
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
      - compiletoo
